package com.dozenx.web.module.interfaceapi.interfaceParam.dao;

import com.dozenx.swagger.annotation.Param;
import com.dozenx.web.module.interfaceapi.interfaceParam.pojo.InterfaceParam;

import java.util.List;
import java.util.Map;

public interface InterfaceParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_params
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_params
     *
     * @mbggenerated
     */
    int insert(InterfaceParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_params
     *
     * @mbggenerated
     */
    int insertSelective(InterfaceParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_params
     *
     * @mbggenerated
     */
    InterfaceParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_params
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InterfaceParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_params
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(int key);

    List<InterfaceParam> selectByInterfaceId(int interfaceid);

    int deleteByInterfaceId(int interfaceid);

    int insertParamsList(@Param(description = "list") List<InterfaceParam> params);

    List<Map<String,Object>> selectByInterfaceIdParams(int interfaceid);
}
