package com.dozenx.web.module.interfaceapi.interfaceParam.pojo;

import java.sql.Timestamp;

public class InterfaceParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface_params.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface_params.param_name
     *
     * @mbggenerated
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface_params.param_type
     *
     * @mbggenerated
     */
    private String paramType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface_params.param_comment
     *
     * @mbggenerated
     */
    private String paramComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface_params.interface_id
     *
     * @mbggenerated
     */
    private int interfaceId;
    private Timestamp createTime;
    private Timestamp updateTime;
    private String paramIn;

    public String getParamIn() {
        return paramIn;
    }

    public void setParamIn(String paramIn) {
        this.paramIn = paramIn;
    }

    public String getParamValue() {
        return paramValue;
    }

    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    private String paramValue;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface_params.id
     *
     * @return the value of interface_params.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface_params.id
     *
     * @param id the value for interface_params.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface_params.param_name
     *
     * @return the value of interface_params.param_name
     *
     * @mbggenerated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface_params.param_name
     *
     * @param paramName the value for interface_params.param_name
     *
     * @mbggenerated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface_params.param_type
     *
     * @return the value of interface_params.param_type
     *
     * @mbggenerated
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface_params.param_type
     *
     * @param paramType the value for interface_params.param_type
     *
     * @mbggenerated
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface_params.param_comment
     *
     * @return the value of interface_params.param_comment
     *
     * @mbggenerated
     */
    public String getParamComment() {
        return paramComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface_params.param_comment
     *
     * @param paramComment the value for interface_params.param_comment
     *
     * @mbggenerated
     */
    public void setParamComment(String paramComment) {
        this.paramComment = paramComment == null ? null : paramComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface_params.interface_id
     *
     * @return the value of interface_params.interface_id
     *
     * @mbggenerated
     */
    public int getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface_params.interface_id
     *
     * @param interfaceId the value for interface_params.interface_id
     *
     * @mbggenerated
     */
    public void setInterfaceId(int interfaceId) {
        this.interfaceId = interfaceId;
    }
    public Timestamp getCreateTime() {
        return createTime;
    }
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime == null ? null : createTime;
    }

    public Timestamp getUpdateTime() {return updateTime; }
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime == null ? null : updateTime;
    }
    public void clear() {
        this.paramType = null;
        this.paramName = null;
        this.paramComment = null;
        this.interfaceId = 0;
        this.createTime = null;
        this.id = null;
    }
}
